### ISSUE TITLE
Unnecessary dependency cycle error

### ISSUE THREAD

**Issue by sohcah** [vercel/turborepo#1163] opened 2022-04-30 18:31 UTC
### What version of Turborepo are you using?

1.2.6

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

Turborepo version 1.2.4 added a check for recursive dependencies to prevent Turborepo freezing.
However, this change stopped some fully working setups from working anymore (instead giving an unnecessary error message).

The recursivity check currently checks whether there any packages which rely on a package which relies on the original package.

### Expected Behavior

Turborepo should only whether there is any recursion in the task graph. Turborepo doesn't freeze if there are 2 packages which rely on each other without relying on any tasks from the other (eg. ^build), only when there are tasks which rely on each other.

### To Reproduce

You can reproduce this bug with the following repo: https://github.com/sohcah/turbo-cycle-bug

If you install turborepo 1.2.6, and run `yarn build`, it fails. 
However, if you switch to turborepo 1.2.3, and run `yarn build`, it succeeds with no issues.

**Comment by sohcah** [comment] 2022-04-30 18:41
I know the example is a bit rubbish (just importing a basic type from 1 project into another, and the other way around). My actual reason (in a private project) for needing recursive dependencies is because I use tRPC for 2-way connection between 2 programs and each project needs to import the AppRouter type from the other project.

**Comment by gsoltis** [comment] 2022-05-03 17:15
I see how that could work, but is there a particular reason for not extracting the common bits out to a separate package?

In the example at least, it looks like something that works more by accident than by design. Without `turbo`, just looking at the various `package.json` files having the `devDependencies` reference each other, you have created a scenario that looks impossible to bootstrap. `a` depends on `b` for building, and `b` depends on `a` for building. The fact that you don't actually need to build to import a type is what makes it work at all.

**Comment by gsoltis** [comment] 2022-05-03 17:49
I think I missed that the connection is two-way. In that case, you can do what you have done, but I think the most stable way to go about it would be something along the lines of:
```
    app1      app2
      |  \    /  |
      |   \  /   |
      |    /\    |
      |   /   \  |
    router1  router2  
```

with the cross-dependencies being `devDependencies` and the direct ones being `dependencies`. Then you have a coherent dependency graph, for `turbo` or other tools.

**Comment by gsoltis** [comment] 2022-05-05 23:24
I'm going to close this, as I don't think we intend to support cyclic dependencies unless we come across a scenario that can't be supported any other way.

**Closed by gsoltis** 2022-05-05 23:24 UTC
