### ISSUE TITLE
Turbo configuration outside of `package.json` in external `config` file

### ISSUE THREAD

**Issue by b12k** [vercel/turborepo#607] opened 2022-01-25 23:16 UTC
### Describe the feature you'd like to request

I would like to have a possibility to configure `turbo` outside of `package.json` in respective `config` file.

There are many libs which are placing its configs into `package.json` so it can grow really big. 

My personal preference is to use respective config files whenever possible:
- .eslintrc
- .prettierrc
- .npmrc
- .commitlintrc
- .branchnamelint
- and many others...

### Describe the solution you'd like

Besides a possibility to put configuration into `package.json` I would like to be able to configure turbo using:

- `.turborc`
- `turbo.config.json`
- `turbo.config.js` 👈 can be a enabler for dynamic configuration if it is possible to execute it using `node` before passing to `turbo`.

[Cosmiconfig](https://www.npmjs.com/package/cosmiconfig) can be used as a reference for this feature request.

Examples:

_Providing same config schema as in `package.json`._

```json
// .turborc OR turbo.config.json
{
  "pipeline": {
    "build": {
      "dependsOn": [
        "^build"
      ],
      "outputs": [
        "dist/**",
        ".next/**"
      ]
    },
    "lint": {
      "outputs": []
    },
    "dev": {
      "cache": false
    }
  }
}
```

```js
// turbo.config.js
module.exports = {
  "pipeline": {
    "build": {
      "dependsOn": [
        "^build"
      ],
      "outputs": [
        "dist/**",
        ".next/**"
      ]
    },
    "lint": {
      "outputs": []
    },
    "dev": {
      "cache": false
    }
  }
}
```

### Describe alternatives you've considered

Current way of placing configuration into `package.json`.

### 🍺🍺🍺
Thank you for an amazing job developing `Turbo` 🐱‍👤

**Comment by jaredpalmer** [comment] 2022-01-25 23:27
Thanks for the write up. @gsoltis is actually working this as we speak. Closing as this is a duplicate of #217

**Closed by jaredpalmer** 2022-01-25 23:27 UTC
