### ISSUE TITLE
this command is not yet implemented for nodejs-npm

### ISSUE THREAD

**Issue by OmgImAlexis** [vercel/turborepo#2152] opened 2022-10-04 06:09 UTC
### What version of Turborepo are you using?

1.5.5

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Windows

### Describe the Bug

When trying to use `turbo prune --scope=app-monitor --docker` I get an error.

I looked for other issues about this and they all mention pnmp not npm.

### Expected Behavior

No error.

### To Reproduce

`turbo prune --scope=app-monitor --docker`

**Comment by chris-olszewski** [comment] 2022-10-04 15:26
Closing this as a duplicate of #1830

**Closed by chris-olszewski** 2022-10-04 15:26 UTC
