### ISSUE TITLE
Turborepo errors out when using yarn pnp 

### ISSUE THREAD

**Issue by itsbth** [vercel/turborepo#488] opened 2022-01-03 13:33 UTC
### What version of Turborepo are you using?

1.0.24

### What package manager are you using / does the bug impact?

Yarn v2/v3 (not supported)

### What operating system are you using?

Linux

### Describe the Bug

`turbo run ...` fails with an error like
```
/home/itsbth/scratch/tr-sample/.pnp.cjs:15363
    throw firstError;
    ^

Error: Qualified path resolution failed - none of those files can be found on the disk.

Source path: /home/itsbth/scratch/tr-sample/.yarn/unplugged/turbo-npm-1.0.24-afce9e06ca/node_modules/turbo/
Not found: /home/itsbth/scratch/tr-sample/.yarn/unplugged/turbo-npm-1.0.24-afce9e06ca/node_modules/turbo/
Not found: /home/itsbth/scratch/tr-sample/.yarn/unplugged/turbo-npm-1.0.24-afce9e06ca/node_modules/turbo/.js
Not found: /home/itsbth/scratch/tr-sample/.yarn/unplugged/turbo-npm-1.0.24-afce9e06ca/node_modules/turbo/.json
Not found: /home/itsbth/scratch/tr-sample/.yarn/unplugged/turbo-npm-1.0.24-afce9e06ca/node_modules/turbo/.node
Not found: /home/itsbth/scratch/tr-sample/.yarn/unplugged/turbo-npm-1.0.24-afce9e06ca/node_modules/turbo/index.js
Not found: /home/itsbth/scratch/tr-sample/.yarn/unplugged/turbo-npm-1.0.24-afce9e06ca/node_modules/turbo/index.json
Not found: /home/itsbth/scratch/tr-sample/.yarn/unplugged/turbo-npm-1.0.24-afce9e06ca/node_modules/turbo/index.node

Require stack:
- /home/itsbth/scratch/tr-sample/.yarn/unplugged/turbo-npm-1.0.24-afce9e06ca/node_modules/turbo/node-platform.js
- /home/itsbth/scratch/tr-sample/.yarn/unplugged/turbo-npm-1.0.24-afce9e06ca/node_modules/turbo/bin/turbo
    at Function.external_module_.Module._resolveFilename (/home/itsbth/scratch/tr-sample/.pnp.cjs:15362:55)
    at Function.resolve (internal/modules/cjs/helpers.js:98:19)
    at generateBinPath (/home/itsbth/scratch/tr-sample/.yarn/unplugged/turbo-npm-1.0.24-afce9e06ca/node_modules/turbo/node-platform.js:110:46)
    at Object.<anonymous> (/home/itsbth/scratch/tr-sample/.yarn/unplugged/turbo-npm-1.0.24-afce9e06ca/node_modules/turbo/bin/turbo:6:3)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.external_module_.Module._load (/home/itsbth/scratch/tr-sample/.pnp.cjs:15211:14)
    at Function.moduleExports.runMain (/home/itsbth/scratch/tr-sample/.pnp.cjs:15412:31)
    at internal/main/run_main_module.js:17:47
```

It looks like there's some code to try to support pnp, but as the turbo package doesn't have any importable code require.resolve (https://github.com/vercel/turborepo/blob/cbc65fd7dc1ccf18f490d87a0db7ef469571368e/cli/npm/turbo-install/node-platform.js#L110) throws an error. On yarn 3.1.1 (latest as of now) turbo (and turbo-linux-64) appears to be unplugged by default, so it works when you comment out that section (alternatively, adding an empty index.js will make require.resolve work).

### Expected Behavior

It should not crash.

### To Reproduce

1. `npx create-turbo@latest`
2. Choose a directory and package manager yarn.
3. `cd <directory>`
4. `yarn set version stable`
5. `yarn` (migrates the lockfile and sets the linker to node-modules).
6. Turborepo (mostly?) works here.
7. `sed -i '/node-modules/d' .yarnrc.yml` (set linker mode to the default pnp).
8. `yarn`
9. `yarn build` (fails with the above error).

(Note: Even after applying one of the workarounds mentioned earlier the example project still doesn't build with pnp, even in loose mode, but turbo appears to be working)

**Comment by jaredpalmer** [comment] 2022-01-03 14:04
Sorry about this, Turbo does not work with v2 yet. Closing as this is duplicate of #264.

**Closed by jaredpalmer** 2022-01-03 14:04 UTC

**Comment by itsbth** [comment] 2022-01-03 14:21
This is a rather specific bug in code that appears to explicitly try to handle yarn 2+ pnp (and indeed it would have worked without that code as long as turbo is unplugged).
If you don't want to fix it until proper yarn 2+ support, would you accept a PR fixing this specific issue in the meantime?
