### ISSUE TITLE
Turbo gen hangs when used with `--root`

### ISSUE THREAD

**Issue by moltar** [vercel/turborepo#8709] opened 2024-07-10 13:39 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

N/A

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Which canary version will you have in your reproduction?

N/A

### Describe the Bug

Warning: I use `@turbo/gen` directly in isolation, without `turbo` CLI.

When running `gen` from a workspace project, referencing the root, like so:

```sh
node_modules/.bin/gen run --root="../../"
```

Where `../../` _is_ the workspace root (where `.git` dir is).

The CLI hangs, with `node` process taking 99% of the CPU and the process never exits.

### Expected Behavior

Provide selection of generators.

### To Reproduce

1. Add `@turbo/gen` to a workspace sub-project
2. `node_modules/.bin/gen run --root="../../"`

### Additional context

N/A

**Comment by chris-olszewski** [comment] 2024-11-15 15:42
Closing as I was unable to reproduce. If you're still encountering this issue please reopen and provide a reproduction repository.

**Closed by chris-olszewski** 2024-11-15 15:42 UTC
Labels: kind: bug, needs: triage
