### ISSUE TITLE
[turborepo] Error: `timed out waiting for cookie`

### ISSUE THREAD

**Issue by thany** [vercel/turborepo#3800] opened 2023-02-14 13:33 UTC
### What version of Turborepo are you using?

1.7.4

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Windows

### Describe the Bug

First of all, the [starter guide](https://turbo.build/repo/docs/getting-started/create-new) instructs to execute `turbo build` but the command `turbo` doesn't exist. And no amount of saying so in the starter guide will make it come into existence 😘

I you want people to have the `turbo` command available, instruct to install it globally, or change the documentation to not require it, please.

Other than that, when I carry on by executing `npm run build` instead, it outputs what feels like a problem.

```
docs:build: Failed to mark outputs as cached for docs#build: rpc error: code = Unknown desc = timed out waiting for cookie
web:build: Failed to mark outputs as cached for web#build: rpc error: code = Unknown desc = timed out waiting for cookie
```

Probably has to do with remote caching, but we're not using that yet. So why is it waiting for a cookie that it isn't supposed to receive in the first place??

### Expected Behavior

No error. Don't do anything remote if remote cache hasn't been set up at all.

### To Reproduce

Follow the starter guide. Possibly needs a clean environment. Please choose `npm` as the package manager.

**Comment by tom2strobl** [comment] 2023-02-21 09:13
Experiencing the same – no remote cache set up (yet), still getting the message. 1.8.1 on macOS arm64.

I can add to the discussion that the rpc thing is happening both on start:
```Failed to check if we can skip restoring outputs for <repo>#<job>: rpc error: code = Unknown desc = timed out waiting for cookie. Proceeding to check cache```
and on end of a run:
```Failed to mark outputs as cached for <repo>#<job>: rpc error: code = Unknown desc = timed out waiting for cookie```

Related: https://github.com/vercel/turbo/issues/2790 https://github.com/vercel/turbo/issues/2034#issuecomment-1377525355

**Comment by chandlervdw** [comment] 2023-02-21 16:26
Error logs give the following after running `turbo daemon start`
```
timed out waiting for initial fsevents cookie: code
timed out waiting for initial fsevents cookie: filewatching failed to start
```
I'm on MBP M1, Ventura 13.2

**Comment by jtlapp** [comment] 2023-02-27 03:49
I'm building but with this bizarre notice. Turbo version 1.8.2 on a Mac. pnpm 7.26.3.

```
• Packages in scope: @fieldzoo/kysely-repo
• Running build in 1 packages
• Remote caching disabled
@fieldzoo/kysely-repo:build: Failed to check if we can skip restoring outputs for 
  @fieldzoo/kysely-repo#build: rpc error: code = Unknown desc = timed out waiting
  for cookie. Proceeding to check cache

 Tasks:    1 successful, 1 total
Cached:    0 cached, 1 total
  Time:    1.73s 
```

(I added some line breaks to make it more readable.)

If I delete all `.turbo` and `node_modules` directories, `pnpm install` again, then it builds without trouble.

This is happening repeatedly. I get about 5 builds in before it starts up. I'm not sure what starts it.

**Comment by steveluscher** [comment] 2023-05-28 04:06
Duplicate of #2790?

**Comment by vhscom** [comment] 2024-01-30 21:21
If you landed here because you started seeing `WARNING` messages in your `turbo foo` output but don't use the Daemon and scoff at the idea of polluting your package manifest with `--no-daemon` flags you may find your solution [here](https://stackoverflow.com/a/76498093/712334):

```sh
npx turbo daemon clean
```

**Closed** 2024-11-08 15:43 UTC
Labels: kind: bug

**Comment by thany** [comment] 2024-11-09 22:14
> we moved from Go to Rust

Presumably that's not the only thing that's changed then, has it? Switching languages *only* should theoretically result in the same program.

Anyway, I'll check it shortly.
