### ISSUE TITLE
Builds get stuck with nextjs output file tracing enabled

### ISSUE THREAD

**Issue by dlehmhus** [vercel/turborepo#1719] opened 2022-08-18 10:57 UTC
### What version of Turborepo are you using?

1.4.3

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

When enabling nextjs [Output File Tracing](https://nextjs.org/docs/advanced-features/output-file-tracing), turbo builds get stuck: <img width="1072" alt="Screenshot 2022-08-18 at 12 36 18" src="https://user-images.githubusercontent.com/27899554/185375217-ff81a7ac-db82-4f4e-b016-2849870d4a80.png">

When running the same build script without turbo, the task exits successfully.

This issue happens with turbo >= 1.3.0. Version 1.2.16 works as expected.
 

### Expected Behavior

Turbo should not get stuck while caching artifacts.

### To Reproduce

1. Clone [Repo](https://github.com/dlehmhus/turbo-build-stuck-example)
2. `pnpm install`
3. `pnpm run build --filter=docs` (never finishes)
4. The example repo contains a second nextjs project configures without output file tracing for comparison:
`pnpm run build --filter=web`

**Comment by benweiser** [comment] 2022-08-18 14:49
I'm having the same issue. This is all it takes for the build to hang using the turbo starter https://github.com/benweiser/standalone-build-turbo/commit/be158bad70ed0c9fa688338a53fae816a2bd01cf

**Comment by chris-olszewski** [comment] 2022-08-18 20:31
Thanks for providing the repro. It looks like this is caused by an issue with how Turbo handles symlinks. #1453 should address this

**Comment by tknickman** [comment] 2022-08-25 16:58
@dlehmhus this should be fixed in the latest canary

**Comment by dlehmhus** [comment] 2022-08-26 10:15
@tknickman it works as expected with the latest canary. Thanks for fixing the issue 👍

**Closed** 2022-08-26 10:15 UTC
Labels: kind: bug, confirmed
