### ISSUE TITLE
Always getting "cache miss" in a simple lint task

### ISSUE THREAD

**Issue by GiancarlosIO** [vercel/turborepo#2029] opened 2022-09-21 18:10 UTC
### What version of Turborepo are you using?

1.4.7

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

Turborepo always shows a `cache miss` even if the input files have not changed.

### Expected Behavior

Turborepo must hit the cache if the input files have not changed.

### To Reproduce

1. `git clone https://github.com/GiancarlosIO/turbo-cache-miss-bug.git`
2. `pnpm install`
3. `pnpm lint`
4. run `pnpm lint` again to see a "cache miss" from turborepo 😢

**Comment by gnohj** [comment] 2022-09-22 23:22
same issue... rolling back to 1.4.6 works

**Comment by gsoltis** [comment] 2022-09-22 23:31
I think I've identified the regression, our hash became unstable due to the new environment variable fields not being sorted. Fixed in #2054

**Comment by GiancarlosIO** [comment] 2022-09-23 00:04
thanks @gsoltis !

**Comment by gnohj** [comment] 2022-09-23 13:48
@gsoltis upgraded to 1.5.2.. something is stil causing the hash to become unstable.. I get full turbo now, but its not consistent

**Comment by johnschult** [comment] 2022-09-23 14:06
Same here... I can run a `lint` task 3 times one after another, get FULL TURBO three times and then run it again and get a cache miss. No files changed. I should mention that this is isolated to `lint`, it happens when building as well.

**Comment by johnschult** [comment] 2022-09-23 15:30
I feel like this is related to using .env files for my two nextjs apps, both use next auth and both set NEXTAUTH_* environment vars during their lint and build from the .env file.

I don't feel like setting them like the docs say to is very friendly for developers who might have different settings

https://turborepo.org/docs/core-concepts/caching#invisible-environment-variables

**Comment by gsoltis** [comment] 2022-09-23 16:59
@johnschult re: vscode, that's pretty bizarre. If you manage to reproduce it, could you open a new issue?

**Comment by gsoltis** [comment] 2022-09-23 16:59
@gnohj reopening and looking into `dependsOn`

**Comment by johnschult** [comment] 2022-09-23 17:03
> @johnschult re: vscode, that's pretty bizarre. If you manage to reproduce it, could you open a new issue?

I remove my previous, because it turned out to be not accurate. I'm still getting the same kind of inconsistent behavior as far as cache misses.

**Comment by gsoltis** [comment] 2022-09-23 17:05
@johnschult do you have multiple entries in `dependsOn` for your tasks, similar to https://github.com/vercel/turborepo/issues/2029#issuecomment-1256240402 ?

**Comment by johnschult** [comment] 2022-09-23 17:06
No

**Comment by johnschult** [comment] 2022-09-23 17:16
I am running just the lint task and filtering only the two Next JS apps, and like I said above, I get  full turbo one time, then cache miss the next, and then maybe I will get three full turbos, then another cache miss. It seems random, although I doubt it is 😄

**Comment by johnschult** [comment] 2022-09-23 17:28
And to top it off, I created a new turbo project, `my-turborepo` which I know also has two NextJS apps in it and `tsconfig` and it caches fine **every single time**.  I am feeling like this has something to do with environment variables, but I am not including any of them I using (yet) in the the pipeline.

**Closed** 2022-09-23 18:15 UTC

**Comment by gnohj** [comment] 2022-09-23 21:10
still getting the same issue w/ `1.5.3`

**Comment by gsoltis** [comment] 2022-09-23 21:16
@gnohj is your setup similar to the repro posted from this bug? If not, can you open a new issue with a minimal repro for your setup?

Otherwise, I can reopen this and we'll have to dig deeper on this one. FWIW I can no longer reproduce the issue with the repository linked in this issue, but maybe I missed something or there's something unique to your setup that we need to find.

**Comment by gnohj** [comment] 2022-09-25 19:39
@gsoltis couldn't repro it for the life of me.. was about to call it quits yesterday.. then got everything working on `1.5.3` by simply deleting/reinstalling the `pnpm lockfile`.. :man_shrugging:

**Comment by gnohj** [comment] 2022-09-27 15:55
@gsoltis the issue is back and pnpm lockfile seems to be the underlying problem

**Comment by gsoltis** [comment] 2022-09-27 16:02
@gnohj We're tracking the pnpm-related issue in #2075
