### ISSUE TITLE
Intermittent HTTP cache GET/PUT silent failures.

### ISSUE THREAD

**Issue by adamelmore** [vercel/turborepo#487] opened 2022-01-03 13:17 UTC
### What version of Turborepo are you using?

1.0.24

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Linux

### Describe the Bug

I'm seeing intermittent cache misses that I believe to be caused by a failure to PUT/GET a given cache key to/from Vercel. In most cases I'm seeing no log output to indicate that the HTTP request failed—this is why I'm unsure whether the failure occurs on PUT or GET—but, on one occasion I saw some log output in Vercel that may be helpful. See below.

First run, this behavior is expected; this cache entry should not exist, yet, so the build is executed:
```
2022-01-03T11:42:43.854Z [DEBUG] run.api:build: start
2022-01-03T11:42:43.854Z [DEBUG] run.api:build: task output globs: outputs=[".turbo/turbo-build.log", "cdk.out/**"]
2022-01-03T11:42:43.854Z [DEBUG] run.api:build: task hash: value=3dd8da4e3f3dd6b0
2022-01-03T11:42:43.854Z [DEBUG] run.api:build: log file: path=apps/api/.turbo/turbo-build.log
2022-01-03T11:42:43.855Z [DEBUG] run: performing request: method=GET url=https://api.vercel.com/v8/artifacts/3dd8da4e3f3dd6b0?slug=***

...

api:build: cache miss, executing 3dd8da4e3f3dd6b0

...

2022-01-03T11:43:10.928Z [DEBUG] run.api:build: caching output: outputs=[".turbo/turbo-build.log", "cdk.out/**"]
2022-01-03T11:43:10.945Z [DEBUG] run.api:build: done: status=complete duration=27.091337379s
2022-01-03T11:43:11.355Z [DEBUG] run: performing request: method=PUT url=https://api.vercel.com/v8/artifacts/3dd8da4e3f3dd6b0?slug=***
```

I then re-run the job and see an unexpected cache miss:
```
2022-01-03T12:06:04.257Z [DEBUG] run.api:build: start
2022-01-03T12:06:04.258Z [DEBUG] run.api:build: task output globs: outputs=[".turbo/turbo-build.log", "cdk.out/**"]
2022-01-03T12:06:04.258Z [DEBUG] run.api:build: task hash: value=3dd8da4e3f3dd6b0
2022-01-03T12:06:04.259Z [DEBUG] run.api:build: log file: path=apps/api/.turbo/turbo-build.log
2022-01-03T12:06:04.259Z [DEBUG] run: performing request: method=GET url=https://api.vercel.com/v8/artifacts/3dd8da4e3f3dd6b0?slug=***

...

api:build: cache miss, executing 3dd8da4e3f3dd6b0

...

2022-01-03T12:06:31.097Z [DEBUG] run.api:build: caching output: outputs=[".turbo/turbo-build.log", "cdk.out/**"]
2022-01-03T12:06:31.118Z [DEBUG] run.api:build: done: status=complete duration=26.860623477s
2022-01-03T12:06:31.644Z [DEBUG] run: performing request: method=PUT url=https://api.vercel.com/v8/artifacts/3dd8da4e3f3dd6b0?slug=***
```

The above output is from GitHub Actions. In one instance (not the above case), I did see the following log output in Vercel that may be a hint:
```
2022-01-02T12:17:21.421Z [DEBUG] run.web:build: done: status=complete duration=25.849629175s
--
06:17:21.423 | [ERROR] Error uploading artifacts to HTTP cache: archive/tar: write too long
```

The cache artifacts for the `api:build` task in the GitHub Actions case are 2.2 MB (zipped). The artifacts for the `web:build` task in Vercel (that had the visible write error) are 19.7 MB (zipped).

### Expected Behavior

I expect that a given cache key will be successfully PUT to the Vercel remote cache and then retrieved on subsequent runs when a matching hash is calculated.

### To Reproduce

As mentioned, that cache artifacts where I've seen failures are 2.2 MB (zipped) and 19.7 MB (zipped). I wouldn't expect that the actual contents of the cache are pertinent, but I can provide them if needed.

In terms of repro steps, I'm running turbo in GitHub Actions to deploy a CDK app to AWS, and in Vercel to deploy a Next.js app. I've seen these intermittent failures on both platforms.

**Comment by jaredpalmer** [comment] 2022-01-03 13:53
Thanks for the great write up. Will investigate

**Comment by ThibautMarechal** [comment] 2022-03-20 13:33
It seems to be fixed with this https://github.com/vercel/turborepo/pull/895
I cannot reproduced it since I update to the version [1.1.7-canary.5](https://github.com/vercel/turborepo/releases/tag/v1.1.7-canary.5)

**Comment by ThibautMarechal** [comment] 2022-03-26 16:34
nevermind, it happen to me again multiple times.
But i'm on windows, using yarn V1 & turborepo 1.1.9

**Comment by mcrowder65** [comment] 2022-04-20 21:22
I also run into this intermittently. Using mac, yarn v1 & turborepo 1.2.5-canary.1 

Also see it on jenkins running linux.

**Comment by maschwenk** [comment] 2022-05-06 16:24
It'd also be good to be able to log the name of the package that has the issue, because to be honest I'd like to know which particular package is the problem but it's not clear to me from there.

**Comment by sppatel** [comment] 2022-05-12 21:20
Seeing this as well locally publishing to a custom remote cache.

**Comment by sppatel** [comment] 2022-05-17 18:55
I don't think this is a file limit issue.  The latest release of turbo logs the file which this is happening and in my case when it occurs its always the log file - which for my operations should be essentially empty.  (e.g eslint, prettier, etc).  These log files which error out are in bytes, not megabytes.

**Comment by maschwenk** [comment] 2022-05-24 19:28
@sppatel I can confirm I had the same issue, and the file in question (now that it's logging 🎉 ) was also a very short logfile

**Comment by maschwenk** [comment] 2022-05-24 19:44
https://pkg.go.dev/archive/tar@go1.18.2#Writer.Write @jaredpalmer / @sppatel interestingly here it says that `write too long` error is returned when

> Write writes to the current file in the tar archive. Write returns the error ErrWriteTooLong if more than Header.Size bytes are written after WriteHeader.

I'm not sure I fully understand that error. It seems to suggest that between the time where we declare the header size and the time we actually write to it, the file sizes are larger? Or something?

**Comment by nathanhammond** [comment] 2022-05-25 04:38
A quick serialization of things we're talking about:

***

Encountering this issue likely means that the cache would have been bad and should not be reused. That it fails in this scenario is likely the better of two bad outcomes.

***

The place where we generate the header:
https://github.com/vercel/turborepo/blob/63a07b9e25a586d82f5c130182096fbebf3714eb/cli/internal/cache/cache_http.go#L109

Is distant from the place where we write the file:
https://github.com/vercel/turborepo/blob/63a07b9e25a586d82f5c130182096fbebf3714eb/cli/internal/cache/cache_http.go#L134

We do nothing to prevent reading or writing to the outputs in that gap. Addressing this, however, will likely only change the symptom of the bug—hopefully pushing it back into the stack which is causing the problem, but also possibly just ending up serializing the `tar` process to occur *after* the other writer has completed its operation.

***

We know of *at least* one source of guaranteed issues with this where multiple commands write their outputs to the same path. We need strict ordering of output directories considered in our DAG to address that. It also sounds like there may be an issue with our logging and piping content to a file as high-priority correctness bugs. We intend to address all of the places in `turbo` that can trigger this but at some point we reach "you're running a dev server in a separate terminal session" and the solution is "don't do that" or lots of (presumably) expensive file locking/unlocking or FUSE-mounts at the output directories.

**Comment by ThibautMarechal** [comment] 2022-05-30 16:09
I can confirm that the problem didn't happen since the update 💯

**Comment by maschwenk** [comment] 2022-05-30 16:17
@ThibautMarechal same, though it was pretty intermittent in the first place 🎉 

thanks @jaredpalmer / @nathanhammond

**Comment by gsoltis** [comment] 2022-06-03 03:26
Closing, happy to reopen if necessary.

**Closed by gsoltis** 2022-06-03 03:26 UTC
Labels: kind: bug, needs investigation

**Comment by mkotsollaris** [comment] 2022-06-06 23:12
I am getting `cache miss` all the time, even though I am pretty sure I have configured CircleCI secrets accordingly. Here's [my repo ](https://github.com/mkotsollaris/turbo-example)+ [CircleCi logs](https://app.circleci.com/pipelines/github/mkotsollaris/turbo-example/8/workflows/98a01724-186c-480f-819b-fd4b872bbb7f/jobs/11): 

Am I missing something?

**Comment by gsoltis** [comment] 2022-06-06 23:29
@mkotsollaris Can you file a separate issue for us to track? It looks like a separate issue from what is described here (individual http requests failing).

**Comment by mkotsollaris** [comment] 2022-06-06 23:45
Thanks https://github.com/vercel/turborepo/issues/1343
