### ISSUE TITLE
Not caching with identical inputs

### ISSUE THREAD

**Issue by iamnafets** [vercel/turborepo#6833] opened 2023-12-20 21:30 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

None.

### What package manager are you using / does the bug impact?

Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Mac

### Which canary version will you have in your reproduction?

1.11.3-canary.0

### Describe the Bug

Re-running turbo multiple times produces a cache miss consistently in the same package (1 of 20). The outputs using `--summarize` show identical `hash` and `hashOfExternalDependencies` but both have `status`:`MISS`.

![image](https://github.com/vercel/turbo/assets/93804/2e94f839-8af5-4e20-85a1-47ad79c11232)
![image](https://github.com/vercel/turbo/assets/93804/9cd6791c-3270-4128-b6b7-71a606b33dc6)

### Expected Behavior

This should be cached as the inputs are unchanged, the dependencies are unchanged, and I've run it multiple times.

### To Reproduce

Unclear. I could use some guidance on places to look here.

**Comment by iamnafets** [comment] 2023-12-20 21:30
I'll try to create a repro repository. Any hints in the meantime would be helpful.

**Comment by tknickman** [comment] 2023-12-20 21:32
Hey @iamnafets, thanks for the report - if you can create a reproduction starting from `npx create-turbo@latest`, and then pushing that up to a public repo with any additional instructions to reproduce that would be very helpful. Thanks!

**Comment by mehulkar** [comment] 2023-12-22 18:51
`--summarize` output could be wrong. The `timeSaved: 0` reminds me of a bug where if the daemon didn't detect any changes to `outputs`, it would skip restoring the cache. In that case, we wouldn't know how much time you saved on this cache hit (because we never checked the cache!). I [had fixed this before in the Go codepath](https://github.com/vercel/turbo/pull/5101). That `timeSaved: 0`, if it is indeed the same code path, it's possible that this `cache:miss` property is getting populated incorrectly.

Do you see `FULL TURBO` in the output (not in `--summarize`) when you run those two builds?

**Comment by iamnafets** [comment] 2023-12-22 20:05
No FULL TURBO because it's missing the cache for this particular package. I managed to bisect this back to a symlink, it seems like if you have a symlink in the inputs, despite them having the same _content_ it blows the cache. I unfortunately don't have time to set up a repro repository for this since I've been able to unblock myself but effectively I had 2 workspaces:

A/foo
B/foo -> ../A/foo

B's cache was always a miss.

**Comment by mehulkar** [comment] 2024-01-24 14:59
@iamnafets I tried reproducing with a symlink with `1.11.4-canary.1`, and was not able to reproduce: https://github.com/mehulkar/turbo-issue-6833.

If this minimal reproduction matches your setup, can you try the new canary? We have seen some recent issues with "long" symlinks names that may be the cause of your problem as well, so if you could give more realistic paths for your case, that would help. Some of these issues have been fixed in the newest canary however, so please try that and send over any other information you have!

**Closed** 2024-11-13 16:17 UTC
Labels: kind: bug, needs: reproduction, needs: author input, area: caching
