### ISSUE TITLE
Lockfile marshalling does not work with yarn v2/v3 (in node_modules mode)

### ISSUE THREAD

**Issue by Jakst** [vercel/turborepo#268] opened 2021-12-14 16:35 UTC
### What version of Turborepo are you using?

1.0.9

### Describe the Bug

Changes to the `yarn.lock` file do not trigger cache invalidations in yarn v2/v3. Even when using classic `node_modules` mode

### Expected Behavior

A package bump that only affects the yarn.lock file should trigger cache invalidations for the workspaces that depend.

### To Reproduce

Repo: https://github.com/Jakst/turbo-yarn-v3-repro

Steps:
- Checkout the main branch and run `yarn`
- Run `yarn turbo run build`
- Checkout the `modified-lockfile` branch and run `yarn`
- Run `yarn turbo run build`
- Observe that the turbo build caches were not busted by the changes in the lockfile

**Comment by jaredpalmer** [comment] 2021-12-14 17:19
Hey there! Turbo does not (yet) support Yarn v2/3 as stated on the website. 

Please also search before creating a new issue as this is a duplicate of #237

**Closed** 2021-12-14 17:19 UTC
Labels: duplicate

**Comment by Jakst** [comment] 2021-12-14 22:20
Yeah I was aware of that issue, but since that one is fairly unspecific I wanted to highlight this part of the support. Most other things already seem to work quite well.

But you're right of course. I should've commented on that issue instead.
