### ISSUE TITLE
`turbo-ignore` can't find a commit, even though it exists

### ISSUE THREAD

**Issue by iduuck** [vercel/turborepo#2255] opened 2022-10-18 07:46 UTC
### What version of Turborepo are you using?

1.5.2

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

OS is Mac, but CI is on Linux.

When trying to deploy something, I am getting an errorg from `turbo-ignore`.

### Expected Behavior

I am expecting, that `turbo-ignore` works, and does not continue to deploy the app (because there was no change).

The commit, that is reference is available though.

### To Reproduce

Hard to tell, if this is reproducable. I will try to get something up and running, until then, here is the log:

```


Cloning github.com/xxx/xxx (Branch: preview, Commit: fd30856)
--
09:37:08.089 | Cloning completed: 1.284s
09:37:08.091 | Running "npx turbo-ignore"
09:37:09.198 | npx: installed 1 in 1.023s
09:37:09.215 | ≫ Using Turborepo to determine if this project is affected by the commit...
09:37:09.216 | ≫ Inferred `@x/marketing` as scope from "/vercel/path0/apps/marketing/package.json"
09:37:09.217 | ≫ Found previous deployment for project
09:37:09.217 | ≫ Analyzing results of `npx turbo run build --filter=@x/marketing...[89bed4ad4dd822d40934ee113bb34f0c2d0e7f9f] --dry=json`...
09:37:12.287 | exec error: Error: Command failed: npx turbo run build --filter=@bauhow/marketing...[89bed4ad4dd822d40934ee113bb34f0c2d0e7f9f] --dry=json
09:37:12.287 | ERROR  run failed: failed to resolve packages to run: commit 89bed4ad4dd822d40934ee113bb34f0c2d0e7f9f does not exist
```

EDIT:

Just attaching the image, showing that the commit is there:

![CleanShot 2022-10-18 at 09 47 40@2x](https://user-images.githubusercontent.com/325241/196369050-47f406af-4d05-4bf4-8cc9-73683f5e7477.png)

**Comment by iduuck** [comment] 2022-10-20 11:29
**What is your CI environment**
→ I am using GitHub Actions. I am able to invite to the repo, but not to share publicly unfortunately.

**How is it cloning your repo (shallow, up to a certain depth, etc)?**
→ For cloning → I am using Vercel, so this is it. I think it's using the default `git clone` without flags? But honestly don't know.

**Are you manually setting `VERCEL_GIT_PREVIOUS_SHA`?**
→ No.

**Comment by iduuck** [comment] 2022-10-20 11:30
Could this be the case, because I am not "developing" on the main branch, but on a preview branch (like staging)?

**Comment by nathanhammond** [comment] 2022-10-21 05:08
@iduuck Since you're deploying to Vercel we have what we need to diagnose the issue available to us.

@tknickman dpl_EiRN39bbKxMSMC4EzpjLzUrAc8JR

**Comment by nathanhammond** [comment] 2022-10-21 05:14
Of note:
```
cloneDepthArg	--depth=10
cloneDepthType	depth
```

**Comment by nathanhammond** [comment] 2022-10-21 05:58
@tknickman I know what the issue is here: the state of our shallow-since flag. If you look at that deploy's `buildEnv` our env var is not set (we're not hitting the fallback path) and this commit is not within ten.

@iduuck This is a _Vercel_-specific issue, we know what it is, we're actively working on it, and it isn't an issue with `turbo-ignore`.

For now you can set `VERCEL_DEEP_CLONE=1` in your environment variables to ensure that you get proper ignoring behavior, but there will be a point where that is strictly inferior to our default behavior (using `--shallow-since`). Also, the `turbo-ignore` error is not impacting correctness; it's just resulting in additional time spent building. Since you're using remote caching this doesn't make a significant difference.

**Comment by nathanhammond** [comment] 2022-10-21 06:00
@iduuck I recommend leaving your implementation as is; it will automatically start working with the ideal outcomes when we resolve the other issue.

I'm going to close this issue as there is nothing to do here.

**Closed by nathanhammond** 2022-10-21 06:00 UTC
Labels: pkg: turbo-ignore

**Comment by klapec** [comment] 2022-11-03 08:26
@nathanhammond Is there an issue for this on the vercel repo? I'd like to track it as I have several apps within a monorepo and having each and every one rebuild is not ideal.

**Comment by nathanhammond** [comment] 2022-11-03 08:29
Literally working on this right now. No ETA (has to roll out) but 🔜

**Comment by klapec** [comment] 2022-11-03 08:30
Awesome, thank you!

**Comment by leopard930418** [comment] 2022-11-22 09:28
![image](https://user-images.githubusercontent.com/99602557/203277225-0a10b2ad-6d23-4e45-9093-dc489aaa9c6b.png)
Please help me.

**Comment by iduuck** [comment] 2023-02-21 11:30
Hey @nathanhammond, sorry to mention you, but I have the same problem over and over again.

My default branch is `preview`, and I have a `web`, `marketing`, and `sanity` "app" in my monorepo, also I have several "packages" in my monorepo. I am currently working on the `marketing` page, but still the `web` app is deployed over and over again, because of the error from the initial thing.

```
turbo-ignore could not complete - commit does not exist or is unreachable
```

**Comment by klapec** [comment] 2023-03-14 21:29
I'm seeing the same issue once again. I've made a commit in a monorepo that has multiple Vercel projects pointing to different parts of it and a single Vercel project was rebuilt - because of the `commit does not exist or is unreachable` turbo-ignore error. Deployment of every other project has been cancelled, as expected (the commit did not affect any of the projects).

`dpl_58RTurS25hSHtW3ZAjH3PpXs66Ks`

**Comment by nathanhammond** [comment] 2023-03-15 03:27
We had to pause roll out because of side effects. As a consequence of that, you will need to set VERCEL_DEEP_CLONE to make sure that you have enough commits on the build box in order for it to complete the comparison.

This is a consequence of the default cloned depth being 10.

**Comment by jackhkmatthewsBB** [comment] 2023-08-04 16:27
Not completely related but I was having an issue running `npx turbo-ignore` in a github action.

Leaving my problem and solution here incase anyone else with the same issue stumbles across this thread.

When running `npx turbo-ignore` in a github action I was getting:

```
≫   UNKNOWN_ERROR: Error: Command failed: npx turbo run "test" --filter=frontend...[HEAD^] --dry=json
 ERROR  run failed: failed to resolve packages to run: git error: fatal: ambiguous argument 'HEAD^...HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

Turns out by default `actions/checkout@v3` only has access to a single commit so git could not compare the current commit against a previous commit.

Fixed by passing `fetch-depth: 0` to `actions/checkout@v3` - fetches entire git history making previous commits accessible.

https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches
