### ISSUE TITLE
Feature Request: Compatibility with basic ndjson formatting, such as pino-pretty

### ISSUE THREAD

**Issue by erikmellum** [vercel/turborepo#2094] opened 2022-09-27 20:36 UTC
### Describe the feature you'd like to request

I want to have an option to remove the prefix in front of each task that prevents it from being parseable JSON. This would make it possible to use ndjson formatters such as pino-pretty to style log output while running with turbo. http://ndjson.org/

### Describe the solution you'd like

Provide a CLI option to remove the prefix in front of each task that prevents it from being parseable JSON. This would support piping turborepo output into pino-pretty or other ndjson formatters. It could be a new value for `--output-logs` option such as `--output-logs=ndjson`

Example of running with no turborepo (notice the syntax highlighting on the last line due to `yarn run dev | pino-pretty`:

<img width="843" alt="image" src="https://user-images.githubusercontent.com/6475033/192629911-c0c7e494-d7cc-493b-99da-600a91eaff5f.png">

Example of running with turborepo (notice the missing syntax highlighting due to the prefix `fastify-template:dev:` when running `yarn turbo run dev --output-logs=none --filter=fastify-template | pino-pretty`:

<img width="855" alt="image" src="https://user-images.githubusercontent.com/6475033/192630063-667a7552-9a0a-4453-9a02-1ee50571cb38.png">

### Describe alternatives you've considered

I've tried the existing options from: https://turborepo.org/docs/reference/command-line-reference#--output-logs and they do not satisfy my use case.

### What is pino-pretty?

<img width="750" alt="image" src="https://user-images.githubusercontent.com/6475033/192630501-83eb54aa-dc43-49de-a59d-cff045503961.png">

**Comment by chris-olszewski** [comment] 2022-09-28 17:10
Hi, thank you for the detailed issue. I believe this is a duplicate of #901. Adding this feature is on our roadmap, but there's a `sed` command mentioned in the thread that should work as a temporary workaround.

**Closed by chris-olszewski** 2022-09-28 17:10 UTC
