### ISSUE TITLE
When I udpate my npm package,turbo still uses the old node_modules/.cache

### ISSUE THREAD

**Issue by Hongmiaomiao** [vercel/turborepo#1456] opened 2022-06-29 07:22 UTC
### What version of Turborepo are you using?

1.3.1

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Describe the Bug

When I udpate my npm package,turbo still uses the old node_modules/.cache.
I want to debug/update a npm package,but everytime I update package, I find I need to delete the node_modules/.cache first.

### Expected Behavior

I hope when I update my npm package,turbo can update itself.

### To Reproduce

1. use turbo to build
2. update a npm package version
3. you find it will still use the old version util you delete the node_modules/.cache

My tubro.json
```
{
  "pipeline": {
    "build": {
      "dependsOn": [
        "^build"
      ],
      "outputs": [
        "dist/**",
        ".next/**"
      ]
    },
    "build:dev": {
      "dependsOn": []
    },
    "lint": {
      "outputs": []
    },
    "dev": {
      "cache": false
    }
  }
}
```

I also want to know, why I run turbo run dev --parallel --no-cache, it can't help before I delete  node_moduels/.cache

**Comment by nathanhammond** [comment] 2022-06-30 20:34
What you're reporting is likely by design; we do not include any information about the contents of `node_modules` inside of our cache calculation. If you run a build after mutating a package inside of `node_modules` Turborepo will not know that the cache needs to be purged. Further, if you install a package without updating `package.json` that will also not trigger invalidation. However, if you do update `package.json` it will do what you want:

```
~/repos/turbo-vercel-repro (main *)$ git status
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   apps/api/package.json
	modified:   yarn.lock

no changes added to commit (use "git add" and/or "git commit -a")
~/repos/turbo-vercel-repro (main *)$ yarn run build
yarn run v1.22.19
$ turbo run build
• Packages in scope: @acme/api, @acme/utils
• Running build in 2 packages
@acme/utils:build: cache hit, replaying output 0a51811ae984c6fb
@acme/utils:build: warning package.json: No license field
@acme/utils:build: $ tsup src/index.ts --format esm,cjs --dts
@acme/utils:build: CLI Building entry: src/index.ts
@acme/utils:build: CLI Using tsconfig: tsconfig.json
@acme/utils:build: CLI tsup v6.1.2
@acme/utils:build: CLI Target: node14
@acme/utils:build: ESM Build start
@acme/utils:build: CJS Build start
@acme/utils:build: ESM ⚡️ Build success in 248ms
@acme/utils:build: CJS ⚡️ Build success in 23ms
@acme/utils:build: ESM dist/index.mjs 242.00 B
@acme/utils:build: CJS dist/index.js 1.18 KB
@acme/utils:build: DTS Build start
@acme/utils:build: DTS ⚡️ Build success in 383ms
@acme/utils:build: DTS dist/index.d.ts 67.00 B
@acme/api:build: cache miss, executing e4a56c6b12ae0aba
@acme/api:build: $ rimraf build/ && tsc -b

 Tasks:    2 successful, 2 total
Cached:    1 cached, 2 total
  Time:    1.005s 

✨  Done in 1.18s.
```

You can see that adding a new dependency to the `api` workspace successfully triggered a cache invalidation of the `api` workspace.

**Comment by nathanhammond** [comment] 2022-06-30 20:41
`turbo run dev --parallel --no-cache` tells turbo not to write a cache, it doesn't tell turbo to run every task node. You're looking for `--force`.

https://turborepo.org/docs/core-concepts/caching#force-overwrite-cache

**Comment by nathanhammond** [comment] 2022-06-30 20:44
As a workaround for your debugging workflow, I suspect that you can remove `node_modules` from your `.gitignore` which will cause `turbo` to consider `node_modules` as part of its cache invalidation.

I'm going to close this as the behavior you're reporting is as expected, and not a bug.

**Closed by nathanhammond** 2022-06-30 20:44 UTC
