### ISSUE TITLE
globalDependencies not taken into account for files in the root folder

### ISSUE THREAD

**Issue by h22-hub** [vercel/turborepo#886] opened 2022-03-15 18:47 UTC
### What version of Turborepo are you using?

1.1.6

### What package manager are you using / does the bug impact?

npm, pnpm

### What operating system are you using?

Windows

### Describe the Bug

After launching `npx create-turbo@latest prj --use-npm` then changing `turbo.json` to add `globalDependencies` for a file in the root folder, when changing the content of this file, we have a cache hit.

### Expected Behavior

We should have a cache miss.

### To Reproduce

```
npx create-turbo@latest prj --use-npm
cd prj
node -e "const c = require('./turbo.json'); c.globalDependencies= ['./file.js','../file.js','../../file.js']; require('fs').writeFileSync('./turbo.json', JSON.stringify(c, null, 2) , 'utf-8');"
echo "foo" > file.js
npm run build
echo "bar" > file.js
npm run build
```

Last `npm run build` should not use cache

**Comment by gsoltis** [comment] 2022-03-15 20:37
Looks like I can repro. The issue is we're using the full path for resolving the global deps, but then prepending the root path of the repo again when going to hash the file, resulting in a path to a file that doesn't exist.

**Closed** 2022-03-16 21:12 UTC
Labels: kind: bug
