### ISSUE TITLE
run interactive terminal doesn't take user input

### ISSUE THREAD

**Issue by juliusmarminge** [vercel/turborepo#1706] opened 2022-08-16 23:40 UTC
### What version of Turborepo are you using?

1.4.3

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

Maintainer of [create-t3-app](https://github.com/t3-oss/create-t3-app) here. We recently migrated to turborepo and ran into some troubles when running the CLI with it.

Essentially, when running turbo it doesn't accept any user interactions:

![CleanShot 2022-08-17 at 01 35 10](https://user-images.githubusercontent.com/51714798/185002989-abe73e45-6c62-487f-bbae-4e01020b612f.png)

I suspect this is because turbo is running in some concurrency mode and expecting multiple packages? I tested adding the --concurrency=1 to prevent that but it didn't help:

![CleanShot 2022-08-17 at 01 40 24](https://user-images.githubusercontent.com/51714798/185003512-7fb9ac4c-9912-40ad-a579-736a059f8e92.png)

### Expected Behavior

This is the output when running without turbo:

![CleanShot 2022-08-17 at 01 36 33](https://user-images.githubusercontent.com/51714798/185003108-a9d5ac9a-d4a8-46f8-bcd8-4249d084f32e.png)

### To Reproduce

You can clone `create-t3-app` and run `pnpm turbo run dev --filter create-t3-app`, which will execute the CLI.

Should probably occur when running any CLI that takes user input.

**Comment by chris-olszewski** [comment] 2022-08-17 16:44
Closing this as it is a duplicate of #1235

**Closed by chris-olszewski** 2022-08-17 16:44 UTC
