### ISSUE TITLE
Vercel: Trying to install "turbo-linux-64" using npm EACCES: permission denied

### ISSUE THREAD

**Issue by abusada** [vercel/turborepo#390] opened 2021-12-21 09:09 UTC
### What version of Turborepo are you using?

1.0.19

### Describe the Bug

I'm following this guide https://vercel.com/docs/concepts/git/monorepos#turborepo
Trying to deploy an app on vercel, the app is inside a monorepo that is generated with turbo cli.

I have changed the BUILD COMMAND to:
```
cd ../.. && npx turbo run build --scope=@scope/app --includeDependencies --no-deps
```

And I get the following output: 
![screenshot- 2021-12-21 at 10 04 49@2x](https://user-images.githubusercontent.com/2572320/146902541-fbde8648-313f-4006-84c6-8633b8fbd1f5.jpg)

### Expected Behavior

The expected behavior is of course that following [this guide](https://vercel.com/docs/concepts/git/monorepos#turborepo) should simply work.

### To Reproduce

* Include source files outside of the Root Directory in the Build Step is checked:
![screenshot- 2021-12-21 at 10 12 21@2x](https://user-images.githubusercontent.com/2572320/146903430-f901dcc3-3c37-45f4-a306-9a50fd102ae4.jpg)

* packae.json in the root directory: 
```
{
    "version": "0.0.0",
    "private": true,
    "workspaces": [
      "apps/*",
      "packages/*"
    ],
    "scripts": {
      "build": "turbo run build",
      "dev": "turbo run dev --parallel",
      "lint": "turbo run lint",
      "format": "prettier --write \"**/*.{ts,tsx,md}\""
    },
    "devDependencies": {
      "prettier": "^2.5.1",
      "turbo": "latest"
    },
    "turbo": {
      "baseBranch": "origin/main",
      "npmClient": "npm",
      "pipeline": {
        "build": {
          "dependsOn": [
            "^build"
          ],
          "outputs": [
            "dist/**",
            ".next/**"
          ]
        },
        "lint": {
          "outputs": []
        },
        "dev": {
          "cache": false
        }
      }
    },
    "engines": {
      "npm": ">=7.0.0",
      "node": ">=14.0.0"
    }
  }
```

**Comment by goellner** [comment] 2021-12-21 14:53
same issue here since today, no idea how to fix this one or if it is on Vercel side to fix.

**Comment by joshsny** [comment] 2021-12-21 19:48
Also experiencing this issue as of today. Not sure how to fix this either.

**Comment by lukebussey** [comment] 2021-12-22 01:57
I’m also experiencing the same issue.

I can get past it  with the following install command

    npm install turbo@latest && npm install

But then I run into the next issue:

    web:build: error TS6053: File 'tsconfig/nextjs.json' not found.

**Comment by goellner** [comment] 2021-12-22 08:33
i solved by removing all `package-lock.json` files. now it builds with `yarn` instead of `npm` and it works again

**Comment by abusada** [comment] 2021-12-22 11:29
I confirm that using yarn instead of npm fixed the issue

**Comment by lukebussey** [comment] 2021-12-22 12:50
Also confirmed. Removed the `package-lock.json` and changed the build command to:

    cd ../.. && yarn turbo run build --scope=web --includeDependencies --no-deps

**Comment by joshsny** [comment] 2021-12-22 16:42
yarn turbo run build etc... is giving me error Command "turbo" not found when deploying to Vercel, but working locally. Am I making a silly mistake here?

**Comment by lukebussey** [comment] 2021-12-22 16:46
@joshsny In your turborepo project root, make sure you've run `yarn install`. That fixed that error for me.

**Comment by jaredpalmer** [comment] 2021-12-22 22:59
This is fixed in `turbo@canary`

**Comment by jaredpalmer** [comment] 2021-12-22 23:15
This is now released in turbo@latest. 

SORRRY for the headaches!

**Closed by jaredpalmer** 2021-12-22 23:15 UTC

**Comment by ihadabs** [comment] 2021-12-23 16:53
Same here ...

```
Cloning completed: 1.406s
--
19:48:03.644 | Analyzing source code...
19:48:04.214 | Installing build runtime...
19:48:07.506 | Build runtime installed: 3.292s
19:48:09.718 | No Build Cache available
19:48:10.432 | Installing dependencies...
19:48:10.435 | Detected `package-lock.json` generated by npm 7...
19:48:25.704 |  
19:48:25.704 | added 402 packages in 15s
19:48:25.705 |  
19:48:25.705 | 65 packages are looking for funding
19:48:25.705 | run `npm fund` for details
19:48:25.728 | Detected Next.js version: 12.0.3
19:48:25.924 | Running "cd ../.. && npx turbo run build --scope=docs --includeDependencies --no-deps"
19:48:29.260 | • Packages in scope: docs
19:48:29.260 | • Remote computation caching enabled (experimental)
19:48:29.260 | • Running build in 1 packages
19:48:29.742 | docs:build: cache miss, executing f29a2c64e148c9c9
19:48:29.966 |  
19:48:29.966 | docs:build: > docs@0.0.0 build /vercel/path0/apps/docs
19:48:29.966 | docs:build: > next build
19:48:29.966 |  
19:48:30.694 | docs:build: Attention: Next.js now collects completely anonymous telemetry regarding usage.
19:48:30.694 | docs:build: This information is used to shape Next.js' roadmap and prioritize features.
19:48:30.695 | docs:build: You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
19:48:30.695 | docs:build: https://nextjs.org/telemetry
19:48:30.695 |  
19:48:30.739 | docs:build: info  - Checking validity of types...
19:48:30.997 | docs:build: error TS6053: File 'tsconfig/nextjs.json' not found.
19:48:30.997 |  
19:48:30.997 | docs:build: npm ERR! code ELIFECYCLE
19:48:30.997 | docs:build: npm ERR! errno 1
19:48:30.998 | docs:build: npm ERR! docs@0.0.0 build: `next build`
19:48:30.998 | docs:build: npm ERR! Exit status 1
19:48:30.998 | docs:build: npm ERR!
19:48:30.998 | docs:build: npm ERR! Failed at the docs@0.0.0 build script.
19:48:30.998 | docs:build: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
19:48:30.998 |  
19:48:30.998 | docs:build: npm ERR! A complete log of this run can be found in:
19:48:30.998 | docs:build: npm ERR!     /vercel/.npm/_logs/2021-12-23T16_48_30_987Z-debug.log
19:48:30.998 | docs:build: Error: command finished with error: exit status 1
19:48:31.000 | Command failed: /vercel/.npm/_npx/401/lib/node_modules/turbo/node_modules/turbo-linux-64/bin/turbo run build --scope=docs --includeDependencies --no-deps
19:48:31.012 | Error: Command "cd ../.. && npx turbo run build --scope=docs --includeDependencies --no-deps" exited with 1
```
