### ISSUE TITLE
[WEB-995] Support tsconfig `nodenext`

### ISSUE THREAD

**Issue by padmaia** [vercel/turborepo#4807] opened 2023-05-03 21:18 UTC
<sub>From [SyncLinear.com](https://synclinear.com) | [WEB-995](https://linear.app/vercel/issue/WEB-995/support-tsconfig-nodenext)</sub>

<sub>[PACK-3031](https://linear.app/vercel/issue/PACK-3031/[web-995]-support-tsconfig-nodenext)</sub>

**Comment by wojtekmaj** [comment] 2024-04-04 09:28
It looks like we're nearing Turbo release with 99.7% tests passing, and yet, Turbo is STILL unable to resolve any modules with extensions. I'm getting hundreds and hundreds of errors like:

```

./packages/site-structure/index.ts:1:0
Module not found: Can't resolve './src/siteStructure.js'
> 1 | import { getSiteStructure } from './src/siteStructure.js';
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  2 |
  3 | import type {
  4 |   IPageEntryCollectionPartial,

https://nextjs.org/docs/messages/module-not-found
```

**Comment by Jack-Works** [comment] 2024-05-08 06:13
this blocks me trying `--turbo` in nextjs. we use this feature a lot

**Comment by AlessioGr** [comment] 2024-05-29 04:50
Would be great if this could be added soon! Can't wait to cut my compile times in half.

At [payload](https://github.com/payloadcms/payload) we LOVE supporting the latest and greatest next features. And while turbo works, the lack of nodenext support prevents us from running our test suites against turbo, thus we cannot guarantee turbo will work smoothly.

We are using `moduleResolution: NodeNext` across our entire monorepo, as well as fully-specified imports (crazy, I know, but that way we can ensure that our packages work outside of bundlers as well). Turbo just errors our when it encounters those.

**Comment by wojtekmaj** [comment] 2024-07-04 15:46
_\*Sigh\*_ fine, I'll bite.

Introducing **next-turbopack-nodenext** - a package that patches your Next.js config so that Turbopack could resolve fully specified `.js` extensions leading to TypeScript files in your `src` directory.

https://github.com/wojtekmaj/next-turbopack-nodenext

- Install by executing `npm install next-turbopack-nodenext` or `yarn add next-turbopack-nodenext --dev`.
- Import by adding `import withNodeNext from 'next-turbopack-nodenext'`.
- Use it by wrapping your config `export default withNodeNext(nextConfig)`.

**Comment by wojtekmaj** [comment] 2024-07-08 12:23
@macrozone Not even that should be necessary, unless you're unhappy with the default order the plugin looks for files. If you provide a minimum reproduction I'll be happy to look into this. Also, when you have it, please rather raise an issue against my repo, we don't want to clutter this thread any more than necessary.

**Comment by macrozone** [comment] 2024-07-08 13:48
> @macrozone Not even that should be necessary, unless you're unhappy with the default order the plugin looks for files. If you provide a minimum reproduction I'll be happy to look into this. Also, when you have it, please rather raise an issue against my repo, we don't want to clutter this thread any more than necessary.

fair point. So far i settled with not using turbo pack in nextjs, until this is officially supported with ESM.

**Comment by timneutkens** [comment] 2024-10-21 21:18
[This PR landed a while back](https://github.com/vercel/turborepo/pull/8748) for Turbopack

**Comment by chris-olszewski** [comment] 2024-11-05 19:01
Closing as Turbopack as [moved homes](https://vercel.com/blog/turbopack-moving-homes)

**Closed by chris-olszewski** 2024-11-05 19:01 UTC
Labels: linear: turbopack, owned-by: turbopack, created-by: turbopack
