### ISSUE TITLE
turbo not ignoring node_modules with pnpm workspace globs

### ISSUE THREAD

**Issue by qdozaq** [vercel/turborepo#251] opened 2021-12-13 20:08 UTC
### What version of Turborepo are you using?

1.0.7

### Describe the Bug

In a pnpm workspace using the following rules

```yaml
packages:
  - "packages/**"
```
turbo sees the packages in `node_modules` as other workspace packages and attempts to run commands on them.

this _can_ be worked around by explicitly setting the package name in the `pnpm-workspace.yaml` or by using a single level glob
```yaml
packages:
  - "packages/*"
```

### Expected Behavior

I would expect turbo to understand the pnpm workspace pattern matching and not include `node_modules` as packages

### To Reproduce

Reproduction: https://github.com/qdozaq/turbo-pnpm-workspace-bug

**Comment by jaredpalmer** [comment] 2021-12-13 20:19
Thanks. Sorry you hit this. Known bug. Duplicate of #32.

For now, do not use doublestar in the array, just use single star globs

**Comment by jaredpalmer** [comment] 2021-12-13 20:20
Closing in favor of #32

**Closed by jaredpalmer** 2021-12-13 20:20 UTC
Labels: duplicate
