### ISSUE TITLE
`Warning: Invalid hook call.` when starting nextjs project

### ISSUE THREAD

**Issue by cktsun1031** [vercel/turborepo#1662] opened 2022-08-09 10:31 UTC
### What version of Turborepo are you using?

1.4.2

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Windows

### Describe the Bug

Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app

![image](https://user-images.githubusercontent.com/65409152/183626992-0c412807-70b4-4e70-bbe0-17e8d845751b.png)

### Expected Behavior

I have a different react package installed in other `apps` dir.
Nextjs with React `18.2.0` and other apps with React `18.0.0`

### To Reproduce

```
{
  "name": "app-name",
  "version": "0.0.0",
  "private": true,
  "workspaces": {
    "packages": [
      "packages/*",
      "apps/*"
    ],
    "nohoist": [
      "**/react",
      "**/react/**",
      "**/react-dom",
      "**/react-dom/**",
      "**/react-native",
      "**/react-native/**",
      "**/@react-native-*",
      "**/@react-native-*/**",
      "**/react-native-*",
      "**/react-native-*/**",
      "**/*react-navigation/native*",
      "**/*react-navigation/native*/**",
      "**/expo",
      "**/expo/**",
      "**/@expo",
      "**/@expo/**",
      "**/expo-*",
      "**/expo-*/**",
      "**/metro-*",
      "**/metro-*/**"
    ]
  },
  "scripts": {
    "build": "turbo run build",
    "dev": "turbo run dev --no-cache --parallel",
    "lint": "turbo run lint",
    "format": "prettier -w .",
    "commit": "cz"
  },
  "devDependencies": {
    "commitizen": "^4.2.5",
    "cz-conventional-changelog": "^3.3.0",
    "eslint": "^8.21.0",
    "eslint-config-cktidy": "*",
    "husky": "^8.0.1",
    "lint-staged": "^13.0.3",
    "prettier": "^2.7.1",
    "turbo": "^1.4.2"
  },
  "engines": {
    "npm": ">=8.0.0",
    "node": ">=16.0.0"
  },
  "lint-staged": {
    "*.{js,jsx,ts,tsx}": [
      "eslint --fix"
    ],
    "*.{html,scss,css,vue}": [
      "prettier -w"
    ]
  },
  "config": {
    "commitizen": {
      "path": "cz-conventional-changelog"
    }
  }
}
```

Normally install with yarn and using yarn workspace

**Comment by tknickman** [comment] 2022-08-09 16:58
Hey @cktsun1031 could you provide a reproduction repo? This doesn't sound like an issue with turbo - but I'd be happy to take a look if you could isolate the problem and provide a sample reproduction.

**Comment by cktsun1031** [comment] 2022-08-10 06:36
I can solve the issue by unifying the react version of every projects inside `apps`.
Actually this is not efficient for managing monorepos.
I dont know how to solve it while i am using yarn workspaces

**Comment by tknickman** [comment] 2022-08-10 14:03
You should be able to use different version of react in your apps as long as they're each being deployed individually and don't interdepend on each other. However, this issue often arrises when using different copies of react between an app and a package (or, more generalized, when something depends on something else and they use two different _copies_ of react). 

There are many ways to fix this - don't bundle a copy of react with your packages, use peer dependencies, etc. 

Since this isn't a problem with Turborepo itself I'm going to close this one.

**Closed by tknickman** 2022-08-10 14:03 UTC
