### ISSUE TITLE
starter cpu full load

### ISSUE THREAD

**Issue by wenerme** [vercel/turborepo#205] opened 2021-12-12 15:39 UTC
### What version of Turborepo are you using?

1.0.6

### Describe the Bug

![image](https://user-images.githubusercontent.com/1777211/145718787-63054817-7cfd-45ca-8010-483bca519a53.png)

### Expected Behavior

Don't expected turbor need so much cpu

### To Reproduce

```bash
npx create-turbo@latest
code my-turborepo
cd my-turborepo/
npm run build
npm run dev
```

```
node -v
v16.13.0
npm -v
8.1.4
npx turbo -v
1.0.6
```

neofetch

```
                    'c.          
                 ,xNMM.          ---------------------------
               .OMMMMo           OS: macOS Big Sur 10.16 x86_64
               OMMM0,            Host: MacBookPro15,1
     .;loddo:' loolloddol;.      Kernel: 21.1.0
   cKMMMMMMMMMMNWMMMMMMMMMM0:    Uptime: 13 days, 7 hours
 .KMMMMMMMMMMMMMMMMMMMMMMMWd.    Packages: 449 (brew)
 XMMMMMMMMMMMMMMMMMMMMMMMX.      Shell: bash 5.0.17
;MMMMMMMMMMMMMMMMMMMMMMMM:       Resolution: 1680x1050@2x, 1920x1080@2x, 1920x1080@2x
:MMMMMMMMMMMMMMMMMMMMMMMM:       DE: Aqua
.MMMMMMMMMMMMMMMMMMMMMMMMX.      WM: Quartz Compositor
 kMMMMMMMMMMMMMMMMMMMMMMMMWd.    WM Theme: Blue (Dark)
 .XMMMMMMMMMMMMMMMMMMMMMMMMMMk   Terminal: iTerm2
  .XMMMMMMMMMMMMMMMMMMMMMMMMK.   Terminal Font: Monaco 12
    kMMMMMMMMMMMMMMMMMMMMMMd     CPU: Intel i7-8750H (12) @ 2.20GHz
     ;KMMMMMMMWXXWMMMMMMMk.      GPU: Intel UHD Graphics 630, Radeon Pro 555X
       .cooc,.    .,coo:.        Memory: 18256MiB / 32768MiB
```

**Comment by jaredpalmer** [comment] 2021-12-13 14:46
Can you run with `--heap` and `--cpuprofile` and DM me in https://turborepo.org/discord?

**Comment by danistefanovic** [comment] 2021-12-14 13:35
I experience the same issue that @wenerme describes – brand new monorepo with `npx create-turbo@latest` and a ~100% CPU usage when running `yarn dev`.

Both flags, `--heap` and `--cpuprofile`, don't generate an output (or I can't find it).

```
node -v
v16.12.0
yarn -v
1.22.17
npx turbo -v
1.0.9
```

```
OS: macOS Mojave 10.14.6
Shell: zsh 5.8
Terminal: iTerm2
CPU: Intel i7-4578U (4) @ 3.00GHz
```

**Comment by vavra7** [comment] 2021-12-15 13:54
For me it is **10%** of CPU usage when idle in case I'm running dev command with turbo. Comparing it to running all packages and apps dev commands separately with just yarn then my CPU load is approaching **0%** when idle.

```
                   -`                    vavra@archlinux 
                  .o+`                   --------------- 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Host: Zephyrus M GM501GS 1.0 
               `+oooooo:                 Kernel: 5.15.7-arch1-1 
               -+oooooo+:                Uptime: 5 hours, 3 mins 
             `/:-:++oooo+:               Packages: 1186 (pacman) 
            `/++++/+++++++:              Shell: bash 5.1.12 
           `/++++++++++++++:             Resolution: 1920x1080 
          `/+++ooooooooooooo/`           DE: GNOME 41.2 
         ./ooosssso++osssssso+`          WM: Mutter 
        .oossssso-````/ossssss+`         WM Theme: Adwaita 
       -osssssso.      :ssssssso.        Theme: Adwaita [GTK2/3] 
      :osssssss/        osssso+++.       Icons: Adwaita [GTK2/3] 
     /ossssssss/        +ssssooo/-       Terminal: gnome-terminal 
   `/ossssso+/:-        -:/+osssso+-     CPU: Intel i7-8750H (12) @ 4.100GHz 
  `+sso+:-`                 `.-/+oso:    GPU: NVIDIA GeForce GTX 1070 Mobile 
 `++:.                           `-/+/   Memory: 5745MiB / 32025MiB 
 .`                                 `/                   
```

**Comment by jaredpalmer** [comment] 2021-12-15 14:02
Update: need to pass filenames to these flags. Sorry for confusion 

Can you run with `--heap=heap` and `--cpuprofile=profile` and DM me in https://turborepo.org/discord?

**Comment by vavra7** [comment] 2021-12-15 18:47
> Can you run with `--heap=heap` and `--cpuprofile=profile` and DM me in https://turborepo.org/discord?

I run it with parameters as you instructed and files appeared in root. Not sure what extension of the files should be but they are empty anyway since both have 0 bytes.

**Comment by jonbellah** [comment] 2021-12-16 23:39
Seeing the same cpu load issue. Also getting an empty file when running with the `--heap=heap` and `--cpuprofile=profile` flags.


<img width="595" alt="Screen Shot 2021-12-16 at 4 32 39 PM" src="https://user-images.githubusercontent.com/2601219/146464676-b71f137b-a981-46af-8f23-1ac3fc778d74.png">


```
MacBook Pro (16-inch, 2019)
2.4 GHz 8-Core Intel Core i9
64GB 2667 MHz DDR4
```

**Comment by thien-do** [comment] 2021-12-20 09:00
Also happen on Mac Air M1 :D Almost sold it for the 14 inch but then I found this issue

**Comment by legraphista** [comment] 2021-12-20 17:44
Can replicate on windows too, one core is pegged at 100%.

After creating the repo via `npx create-turbo@latest` and running 
```shell
yarn dev --scope=*docs* --heap=heap --cpuprofile=profile
```
I can confirm that it generates 0 sized files for `heap` and `profile` but I believe that's to be expected as I'm running it under watch mode, and it will never have time to write `heap` & `profile` to disk when closing the program.

Maybe this will help:
- closing the program exits with code 1
- it sometimes leaves orphan processes hanging around, occupying either port 3000 or 3001

**Comment by matthewp** [comment] 2021-12-23 18:00
If you need an open-source example, this happens in the Astro repo: https://github.com/withastro/astro

If you run:

```shell
yarn
yarn dev
```

And wait, you'll see Turbo at 100% CPU.

**Comment by thien-do** [comment] 2021-12-26 04:25
So a workaround is to go to the app directly and run it from there?

**Comment by nmcdaines** [comment] 2022-01-02 10:10
I'm not a go developer and am trying to stumble my way through debugging this issue.
I was looking into how to get the cpuprofile and heap traces; however looking into the code:
- I believe that `pprof.StopCPUProfile()` (see: https://github.com/vercel/turborepo/blob/main/cli/cmd/turbo/main_utils.go#L58-L61) isn't being called and as such the file not being written.
- The reason it's not being called is that the deferred methods aren't being called on SIGINT

I am going to continue to look into how I can get this code to run on SIGINT (any help would be appreciated). Hopefully that might help to find the source of the high cpu utilisation.

**Comment by JoeyEamigh** [comment] 2022-01-02 21:50
+1 - 100% CPU usage on a single thread on Ubuntu 20.04 5950X CPU. When the apps are run separately it idles around 2% or less. Happy to help debug further.

**Comment by marcinbunsch** [comment] 2022-01-09 16:37
I'm getting the same issue, I tracked it to this line: https://github.com/vercel/turborepo/blob/15a11406c196a1e3c4497601fa72b5e5a9b4154f/cli/internal/run/run.go#L344

When I comment it out, rebuild turborepo and run it on the sample, CPU usage drops to 0

**Comment by marcinbunsch** [comment] 2022-01-09 17:10
I think I have an idea what's happening - RunState expects the tasks to run, then finish, but `yarn dev` in examples are actually long-running tasks that watch and rebuild code, so they never finish. Apologies if I'm wrong I don't really know go and just dabbled in the code for 2 hours.

As fas I can see, RunState is responsible for rendering this:

![image](https://user-images.githubusercontent.com/65431/148692415-e1ec55e2-5826-485e-a180-9a7e1a9df1ba.png)

However, I had to set `runOptions.stream` to `false` to actually see this output, but the default is `true` and it's not actually possible to set it to `false`. I'm not really sure how to fix it, the only idea I had was to disable the listener when stream is false:

```
func (r *RunState) Listen(Ui cli.Ui, startAt time.Time) {
	if !r.runOptions.stream {
		return
	}
```

But this will essentially disable RunState and I doubt this is the desired fix. Anyway, hope this helps someone with the proper fix!

**Closed** 2022-01-10 18:10 UTC
Labels: kind: bug, needs investigation
