### ISSUE TITLE
Automatically depend on NEXT_PUBLIC env vars

### ISSUE THREAD

**Issue by jaredpalmer** [vercel/turborepo#1058] opened 2022-04-15 14:50 UTC
### Discussed in https://github.com/vercel/turborepo/discussions/981

<div type='discussions-op-text'>

<sup>Originally posted by **ericmatthys** March 31, 2022</sup>
Given the out of the box support with Vercel and somewhat by extension Next.js, I think it'd be worth considering assuming all `NEXT_PUBLIC` env vars affect the hash used for caching. We have quite a few and now our `turbo.json` is another place we need to track them all. Given that `NEXT_PUBLIC` env vars are used for vars that can baked into in the build, I think it'd be a safe assumption that any env var that begins with `NEXT_PUBLIC` should affect the hash. I believe this would lead to fewer issues from the Vercel community giving Turborepo a try.</div>

**Comment by MattKetmo** [comment] 2022-08-10 06:57
Hello, is this issue fixed?

I read on release 1.4 that "Turborepo will now automatically infer and include public environment variables".
https://turborepo.org/blog/turbo-1-4-0#automatic-environment-variable-inclusion

However when testing looks like it still fail.
Example: 
- I [started a new project](https://github.com/MattKetmo/snippets/tree/turbo-no-undeclared-env-vars-example) using the example/with-tailwind (branch `turbo-no-undeclared-env-vars-example`)
- I [added a `process.env.NEXT_PUBLIC_MY_TOKEN` in index](https://github.com/MattKetmo/snippets/commit/aa585fec371ee7716ff715b2c1b8e2e59d11c05e)
- `turbo run build` it still asking me to add `$NEXT_PUBLIC_MY_TOKEN` as dependencies

```
web:build:
web:build: > web@1.0.0 build
web:build: > next build
web:build:
web:build: info  - Linting and checking validity of types...
web:build:
web:build: Failed to compile.
web:build:
web:build: ./src/pages/index.tsx
web:build: 4:17  Error: $NEXT_PUBLIC_MY_TOKEN is not listed as a dependency in turbo.json  turbo/no-undeclared-env-vars
web:build:
web:build: info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
web:build: npm ERR! Lifecycle script `build` failed with error:
web:build: npm ERR! Error: command failed
web:build: npm ERR!   in workspace: web@1.0.0
web:build: npm ERR!   at location: /Users/ketmo/src/github.com/MattKetmo/snippets/apps/web
web:build: ERROR: command finished with error: command (apps/web) npm run build exited (1)
```

I'm not sure the issue is Turbo missing the framework detection or just the eslint rule (which then should also be fixed).

**Comment by raulmabe** [comment] 2022-09-05 13:34
@MattKetmo  How did you solve the issue? I'm having the same error on build on `create-turbo@1.4.5`

**Comment by tknickman** [comment] 2022-09-06 14:05
All that being said, the core of this issue has been completed, so I'm going to close this one out!

**Closed by tknickman** 2022-09-06 14:05 UTC
Labels: story

**Comment by jonahallibone** [comment] 2022-09-14 19:12
@tknickman No matter how I add my environment variables to the `turbo.json` I get a lint error that they could not be found.
```
Error: $NEXT_PUBLIC_CONTENTFUL_SPACE_ID is not listed as a dependency in turbo.json  turbo/no-undeclared-env-vars
````
on the latest version of turbo

**Comment by tknickman** [comment] 2022-09-16 17:30
@jonahallibone you will need to add the full env var to one of the `dependsOn` lists for this to go away:
So, `$NEXT_PUBLIC_CONTENTFUL_SPACE_ID` instead of just `$CONTENTFUL_SPACE_ID`

**Comment by grempe** [comment] 2022-11-30 17:30
Hi @tknickman 

In your comments you said:

> First, you are correct, and turbo@1.4.3 or greater will automatically include any framework specific env variables so technically they do not need to be included in turbo.json. However, the eslint plugin doesn't know about this.

> It's on our list to make this better (along with better observability into what env vars we're auto detecting / including in the hash)

I searched for an issue to track the improvements you mentioned to have [eslint-config-turbo](https://github.com/vercel/turbo/tree/main/packages/eslint-config-turbo) work properly with `NEXT_PUBLIC_*` environment variables, but I was unable to find one.

Can you please provide a link to the issue that tracks this, or create a new one?

Thanks
