### ISSUE TITLE
turborepo --parallel consumes 100% CPU on one thread

### ISSUE THREAD

**Issue by VanTanev** [vercel/turborepo#521] opened 2022-01-07 13:15 UTC
### What version of Turborepo are you using?

1.0.24

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Linux

### Describe the Bug

Creating an application with `npx create-turbo` and `npm` package manager and running `npm run dev` results in 1 CPU thread spinning at 100%

![image](https://user-images.githubusercontent.com/202527/148548894-bf89d970-165a-4ec0-8f2a-9146a911af13.png)

```
➜  node -v
v16.13.1
➜  npm -v
8.1.2
➜  turbo -v
1.0.24
➜  cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
```
Running inside VMWare, but that should make no difference as no other programs show anomalous behavior.

### Expected Behavior

No 100% CPU usage when turbo is ran with `--parallel`

### To Reproduce

Creating an application with `npx create-turbo` and `npm` package manager and run `npm run dev`.

**Comment by oscarehrling** [comment] 2022-01-07 14:05
Same bug for me.

- Mac
- Yarn `1.22.15`
- Node `16.13.0`
- Turbo `1.0.24`

**Comment by JoeyEamigh** [comment] 2022-01-07 23:18
Possible dupe of #205

**Closed** 2022-01-10 18:10 UTC
