### ISSUE TITLE
"dependsOn" tasks resolved incorrectly

### ISSUE THREAD

**Issue by TxHawks** [vercel/turborepo#1212] opened 2022-05-09 15:50 UTC
### What version of Turborepo are you using?

1.2.8

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

A local dependent tasks (e.g. `"dependsOn": [ "foo" ]`), are executed in depended-on packages in addition to the package itself.

If I have three packages: `a`, `b` and `c`, where `a` depends on `b` which depends on `c` with `workspace:*` for package version.

All packages have a `foo` script that depends on `^build`. The `a` package has a `bar` script that depends on `foo` (no `^`).

When running `turbo run bar`, the `foo` script will be executed in all packages.

This is the dependency graph that shows the problem:
![graph-1652109792221647000](https://user-images.githubusercontent.com/5658514/167447065-4b30a0e3-671a-4b37-8c47-eeca02275fff.jpg)

### Expected Behavior

Only the `foo` script of the `a` package should be executed.

### To Reproduce

I'm made a super basic reproduction repository: https://github.com/TxHawks/turbo-depends-on-bug that should demonstrate the issue. After installing the dependencies, simply run `pnpm turbo run bar`

**Comment by gsoltis** [comment] 2022-05-09 21:41
I think this is a duplicate of #937

**Closed** 2022-05-09 21:42 UTC
