### ISSUE TITLE
Installing turbo@1.5.6 fails on alpine docker images

### ISSUE THREAD

**Issue by laat** [vercel/turborepo#2199] opened 2022-10-11 09:29 UTC
### What version of Turborepo are you using?

1.5.6

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Linux

### Describe the Bug

building this image fails

```Dockerfile
FROM node:18.10.0-alpine
RUN yarn global add turbo@1.5.6
```

install fails with "ENOENT"

output:
```
$ docker build --progress=plain .
#1 [internal] load build definition from Dockerfile
#1 sha256:219a5eda47207c3467eea15b54466bf4979eb140012764d9dd51244b92dd40eb
#1 transferring dockerfile: 43B done
#1 DONE 0.0s

#2 [internal] load .dockerignore
#2 sha256:1c0dad0c54c3d9d4c582f31e0a1b1dd95b303eed90eb035d40c7af8eb1c27c77
#2 transferring context: 2B done
#2 DONE 0.0s

#3 [internal] load metadata for docker.io/library/node:18.10.0-alpine
#3 sha256:fb956a169705918d95acc52a3a635d2b073ec5defd81d30644865cfe2d622756
#3 DONE 0.6s

#4 [1/2] FROM docker.io/library/node:18.10.0-alpine@sha256:f829c27f4f7059609e650023586726a126db25aded0c401e836cb81ab63475ff
#4 sha256:465fb7f1db9311dee890e48030be45109274ae21d82831a97313416ae38517c2
#4 CACHED

#5 [2/2] RUN yarn global add turbo@1.5.6
#5 sha256:2c947373a0826002c889324014e294781537152ff57bc117b25ca53d21f53250
#5 0.263 yarn global v1.22.19
#5 0.301 [1/4] Resolving packages...
#5 0.561 [2/4] Fetching packages...
#5 2.219 [3/4] Linking dependencies...
#5 2.256 [4/4] Building fresh packages...
#5 2.360 error /usr/local/share/.config/yarn/global/node_modules/turbo: Command failed.
#5 2.360 Exit code: 1
#5 2.360 Command: node install.js
#5 2.360 Arguments:
#5 2.360 Directory: /usr/local/share/.config/yarn/global/node_modules/turbo
#5 2.360 Output:
#5 2.360 node:internal/errors:863
#5 2.360   const err = new Error(message);
#5 2.360               ^
#5 2.360
#5 2.360 Error: Command failed: node /usr/local/share/.config/yarn/global/node_modules/turbo/bin/turbo --version
#5 2.360 /usr/local/share/.config/yarn/global/node_modules/turbo/bin/turbo:13
#5 2.360     throw e;
#5 2.360     ^
#5 2.360
#5 2.360 <ref *1> Error: spawnSync /usr/local/share/.config/yarn/global/node_modules/turbo-linux-arm64/bin/turbo ENOENT
#5 2.360     at Object.spawnSync (node:internal/child_process:1110:20)
#5 2.360     at spawnSync (node:child_process:857:24)
#5 2.360     at Object.execFileSync (node:child_process:900:15)
#5 2.360     at Object.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/turbo/bin/turbo:6:28)
#5 2.360     at Module._compile (node:internal/modules/cjs/loader:1149:14)
#5 2.360     at Module._extensions..js (node:internal/modules/cjs/loader:1203:10)
#5 2.360     at Module.load (node:internal/modules/cjs/loader:1027:32)
#5 2.360     at Module._load (node:internal/modules/cjs/loader:868:12)
#5 2.360     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
#5 2.360     at node:internal/main/run_main_module:23:47 {
#5 2.360   errno: -2,
#5 2.360   code: 'ENOENT',
#5 2.360   syscall: 'spawnSync /usr/local/share/.config/yarn/global/node_modules/turbo-linux-arm64/bin/turbo',
#5 2.360   path: '/usr/local/share/.config/yarn/global/node_modules/turbo-linux-arm64/bin/turbo',
#5 2.360   spawnargs: [ '--version' ],
#5 2.360   error: [Circular *1],
#5 2.360   status: null,
#5 2.360   signal: null,
#5 2.360   output: null,
#5 2.360   pid: 40,
#5 2.360   stdout: null,
#5 2.360   stderr: null
#5 2.360 }
#5 2.360
#5 2.360 Node.js v18.10.0
#5 2.360
#5 2.360     at checkExecSyncError (node:child_process:871:11)
#5 2.360     at Object.execFileSync (node:child_process:907:15)
#5 2.360     at validateBinaryVersion (/usr/local/share/.config/yarn/global/node_modules/turbo/install.js:25:6)
#5 2.360     at /usr/local/share/.config/yarn/global/node_modules/turbo/install.js:305:5 {
#5 2.360   status: 1,
#5 2.360   signal: null,
#5 2.360   output: [
#5 2.360     null,
#5 2.360     Buffer(0) [Uint8Array] [],
#5 2.360     Buffer(1250) [Uint8Array] [
#5 2.360        47, 117, 115, 114,  47, 108, 111,  99,  97, 108,  47, 115,
#5 2.360       104,  97, 114, 101,  47,  46,  99, 111, 110, 102, 105, 103,
#5 2.360        47, 121,  97, 114, 110,  47, 103, 108, 111,  98,  97, 108,
#5 2.360        47, 110, 111, 100, 101,  95, 109, 111, 100, 117, 108, 101,
#5 2.360       115,  47, 116, 117, 114,  98, 111,  47,  98, 105, 110,  47,
#5 2.360       116, 117, 114,  98, 111,  58,  49,  51,  10,  32,  32,  32,
#5 2.360        32, 116, 104, 114, 111, 119,  32, 101,  59,  10,  32,  32,
#5 2.360        32,  32,  94,  10,  10,  60, 114, 101, 102,  32,  42,  49,
#5 2.360        62,  32,  69, 114,
#5 2.360       ... 1150 more items
#5 2.360     ]
#5 2.360   ],
#5 2.360   pid: 33,
#5 2.360   stdout: Buffer(0) [Uint8Array] [],
#5 2.360   stderr: Buffer(1250) [Uint8Array] [
#5 2.360      47, 117, 115, 114,  47, 108, 111,  99,  97, 108,  47, 115,
#5 2.360     104,  97, 114, 101,  47,  46,  99, 111, 110, 102, 105, 103,
#5 2.360      47, 121,  97, 114, 110,  47, 103, 108, 111,  98,  97, 108,
#5 2.360      47, 110, 111, 100, 101,  95, 109, 111, 100, 117, 108, 101,
#5 2.360     115,  47, 116, 117, 114,  98, 111,  47,  98, 105, 110,  47,
#5 2.360     116, 117, 114,  98, 111,  58,  49,  51,  10,  32,  32,  32,
#5 2.360      32, 116, 104, 114, 111, 119,  32, 101,  59,  10,  32,  32,
#5 2.360      32,  32,  94,  10,  10,  60, 114, 101, 102,  32,  42,  49,
#5 2.360      62,  32,  69, 114,
#5 2.360     ... 1150 more items
#5 2.360   ]
#5 2.360 }
#5 2.360
#5 2.360 Node.js v18.10.0
#5 2.361 info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
#5 ERROR: executor failed running [/bin/sh -c yarn global add turbo@1.5.6]: exit code: 1
------
 > [2/2] RUN yarn global add turbo@1.5.6:
------
executor failed running [/bin/sh -c yarn global add turbo@1.5.6]: exit code: 1
```

### Expected Behavior

this worked with turbo@1.5.5

### To Reproduce

`docker build --progress=plain .`
or
`docker build --platform=linux/x86_64 --progress=plain .`

**Comment by laat** [comment] 2022-10-11 09:34
It's the same problem as in #2198

**Comment by laat** [comment] 2022-10-11 09:44
This Dockerfile works however, so it might just be a documentation issue.

```Dockerfile
FROM node:18.10.0-alpine
RUN apk add --no-cache libc6-compat
RUN yarn global add turbo@1.5.6
```

**Comment by andreyluchianic** [comment] 2022-10-11 12:06
same error for me running on `node:16-alpine`, however changing turbo 1.5.4 fixed for me 
```dockerfile
FROM node:16-alpine AS builder
RUN apk update
# Set working directory
WORKDIR /app
RUN yarn global add turbo@1.5.4
COPY . .
RUN turbo prune --scope=strapi --docker
```

**Comment by Suniron** [comment] 2022-10-11 12:07
> 

`RUN yarn global add turbo@1.5.5` is also OK 😉

**Comment by alessandrojcm** [comment] 2022-10-11 16:20
Same error with 1.5.6 and alpine, alternatively using ubuntu works with the latest version of turbo (albeit with a bigger image and extra config steps)

**Comment by gsoltis** [comment] 2022-10-11 23:41
I think this is a dupe of #2198

**Closed by gsoltis** 2022-10-11 23:41 UTC
