### ISSUE TITLE
Unnecessary tasks are being run when the target task only exists in some packages

### ISSUE THREAD

**Issue by cjpearson** [vercel/turborepo#9589] opened 2024-12-07 19:36 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

https://github.com/cjpearson/turbo-graph-bug

### Which canary version will you have in your reproduction?

turbo@2.3.4-canary.2

### Enviroment information

```block
CLI:
   Version: 2.3.4-canary.2
   Daemon status: Running
   Package manager: yarn

Platform:
   Architecture: aarch64
   Operating system: macos
   WSL: false
   Available memory (MB): 7456
   Available CPU cores: 11
```

### Expected behavior

In the reproduction, I've edited the starter so the `web` package has an additional `verify` script. This task depends on `web:build`. When running `turbo verify` I would expect `web:build` and `web:verify` to run.

### Actual behavior

`web:build`, `docs:build` and `web:verify` are run despite `docs:build` not being necessary

### To Reproduce

Run `turbo verify` in the reproduction project

### Additional context

https://github.com/vercel/turborepo/discussions/9565

**Comment by chris-olszewski** [comment] 2024-12-11 19:36
Duplicate of https://github.com/vercel/turborepo/issues/9589 closing in favor of that one.

**Closed by chris-olszewski** 2024-12-11 19:36 UTC
Labels: kind: bug, needs: triage
