### ISSUE TITLE
create-turbo - aborting installation in ubuntu 20.4 with all 3 package managers

### ISSUE THREAD

**Issue by hobo1618** [vercel/turborepo#1860] opened 2022-09-05 17:28 UTC
### What version of Turborepo are you using?

latest

### What package manager are you using / does the bug impact?

npm, pnpm, Yarn v1

### What operating system are you using?

Linux

### Describe the Bug

I followed the instructions for initial installation.
ubuntu 20.4. 
npm 8.19.1
yarn 1.22.19
pnpm 7.11.0

I run 
`npx create-turbo@latest`

then I select directory and a package manager, and I get this error:

```
>>> TURBOREPO

>>> Welcome to Turborepo! Let's get you set up with a new codebase.

? Where would you like to create your turborepo? portfolio
? Which package manager do you want to use? npm

Aborting installation.
Unexpected error. Please report it as a bug:
TypeError: import_fs.default.cpSync is not a function
    at run (/home/me/.npm/_npx/e8c68b66aeb1424f/node_modules/create-turbo/dist/index.js:319:21)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

I tried updating npm, restarting, but no idea what this error message means. I tried googling it but can't find anything similar enough for me to understand. Help please!

### Expected Behavior

successful installation

### To Reproduce

no idea.

**Comment by jrthib** [comment] 2022-09-05 17:50
Got this error too

**Comment by pratik-adh** [comment] 2022-09-06 11:37
I also got the same error in macOS Monterey version 12.5.1.

**Comment by pratik-adh** [comment] 2022-09-06 11:38
I also got the same error in **macOS Monterey version 12.5.1**.

**Comment by tknickman** [comment] 2022-09-06 13:52
This should be fixed on node 16 (similar issue: https://github.com/vercel/turborepo/issues/1856)

**Comment by hobo1618** [comment] 2022-09-06 15:12
updated to node v18 and worked perfectly. Thank you tk!

**Closed** 2022-09-06 15:12 UTC

**Comment by gregplaysguitar** [comment] 2022-10-17 08:30
This issue is present for me on Macos, with node 16 - i had to upgrade to node 18 to resolve it

**Comment by AryanJ-NYC** [comment] 2022-10-18 14:58
I've also just hit this issue. So Turborepo requires Node 18? Is that the solution here?

**Comment by jetonk** [comment] 2022-10-20 08:29
I had the same issue in macOS Monterey 12.6, I was using Node version 14.18.0, I upgraded to 16.18.0 and the issue is gone.
