### ISSUE TITLE
Test pipeline fails to re-run after input file change pattern ["**/*.tsx", "**/*.ts"] 

### ISSUE THREAD

**Issue by AddictArts** [vercel/turborepo#2242] opened 2022-10-14 17:22 UTC
### What version of Turborepo are you using?

1.5.6

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Windows

### Describe the Bug

With this pipeline

```
    "test": {
      "cache": false,
      "outputs": [],
      "inputs": ["**/*.tsx", "**/*.ts"]
    },
```

Test is not re-run if *.ts file is changed.

### Expected Behavior

Re-run test pipeline

### To Reproduce

I am using vitest in the test, but should be any that reproduces this, just use that `**/*.ts` pattern.

**Comment by mehulkar** [comment] 2022-10-18 00:35
The issue may be the empty `outputs: []` folder. Can you try removing that line? (not saying that's the final fix, just curious). 

Secondly, we are starting work soon on giving you better insight into how turbo interprets your config (e.g. expanding glob patterns), so hopefully that will help debug situations like this.

**Comment by nathanhammond** [comment] 2022-10-18 04:21
I suspect whatever issue you are experiencing here is not triggered by `turbo`. By specifying `cache: false` you are forcing `turbo` to run the `test` task every single time; _no matter what_ the `inputs` array looks like.

Reproduction steps:
`npx create-turbo@latest --use-npm issue-2242

```diff
diff --git a/apps/web/package.json b/apps/web/package.json
index 37fe4e6..4aaa47e 100644
--- a/apps/web/package.json
+++ b/apps/web/package.json
@@ -6,7 +6,8 @@
     "dev": "next dev",
     "build": "next build",
     "start": "next start",
-    "lint": "next lint"
+    "lint": "next lint",
+    "test": "echo running"
   },
   "dependencies": {
     "next": "12.3.1",
diff --git a/apps/web/pages/index.tsx b/apps/web/pages/index.tsx
index 6ec0887..a00ca70 100644
--- a/apps/web/pages/index.tsx
+++ b/apps/web/pages/index.tsx
@@ -3,7 +3,7 @@ import { Button } from "ui";
 export default function Web() {
   return (
     <div>
-      <h1>Web</h1>
+      <h1>Webby</h1>
       <Button />
     </div>
   );
diff --git a/apps/web/pages/plain.ts b/apps/web/pages/plain.ts
new file mode 100644
index 0000000..3931d60
--- /dev/null
+++ b/apps/web/pages/plain.ts
@@ -0,0 +1,3 @@
+export default function Web() {
+  return "still here";
+}
diff --git a/package.json b/package.json
index e911460..2832b44 100644
--- a/package.json
+++ b/package.json
@@ -10,7 +10,8 @@
     "build": "turbo run build",
     "dev": "turbo run dev --parallel",
     "lint": "turbo run lint",
-    "format": "prettier --write \"**/*.{ts,tsx,md}\""
+    "format": "prettier --write \"**/*.{ts,tsx,md}\"",
+    "test": "turbo run test"
   },
   "devDependencies": {
     "eslint-config-custom": "*",
diff --git a/turbo.json b/turbo.json
index c2601a4..1781bcb 100644
--- a/turbo.json
+++ b/turbo.json
@@ -5,6 +5,11 @@
       "dependsOn": ["^build"],
       "outputs": ["dist/**", ".next/**"]
     },
+    "test": {
+      "cache": false,
+      "outputs": [],
+      "inputs": ["**/*.tsx", "**/*.ts"]
+    },
     "lint": {
       "outputs": []
     },
```

Note specifically that the hash is changing between builds as I modify some of the files that are inputs:
```
~/repos/issue-2242 (main *)$ npm run test     

> issue-2242@0.0.0 test
> turbo run test

• Packages in scope: docs, eslint-config-custom, tsconfig, ui, web
• Running test in 5 packages
• Remote caching disabled
web:test: cache bypass, force executing d99c474dcfb7b4c7
web:test: 
web:test: > web@0.0.0 test
web:test: > echo running
web:test: 
web:test: running

 Tasks:    1 successful, 1 total
Cached:    0 cached, 1 total
  Time:    233ms 

~/repos/issue-2242 (main *)$ npm run test

> issue-2242@0.0.0 test
> turbo run test

• Packages in scope: docs, eslint-config-custom, tsconfig, ui, web
• Running test in 5 packages
• Remote caching disabled
web:test: cache bypass, force executing 1370ee493b9c0d7c
web:test: 
web:test: > web@0.0.0 test
web:test: > echo running
web:test: 
web:test: running

 Tasks:    1 successful, 1 total
Cached:    0 cached, 1 total
  Time:    226ms 
```

I'm closing this for now as I have no reason to suspect that there is an issue. If you can get me more information with complete reproduction steps I'll be happy to reopen!

**Closed by nathanhammond** 2022-10-18 04:21 UTC
Labels: needs: author input, area: turbo-cache

**Comment by AddictArts** [comment] 2022-10-18 18:54
@nathanhammond not using next and I removed `outputs:[]`

The config is
```
    "lint": {
      "inputs": ["**/*.tsx", "**/*.ts"]
    },
    "test": {
      "inputs": ["**/*.tsx", "**/*.ts"]
    },
```

On code changes I only see `vite` `hmr` log messages, no re-running of lint or test.

**Comment by mehulkar** [comment] 2022-10-18 19:15
>  if I had something like vite running in dev mode it would, so turbo has not exited, it would re-run the pipeline. I guess this is a false assertion.

Yes, unfortunately, turbo itself does not implement a "watch" mode. There's some theoretical future in which that may be possible, but for long running tasks that don't exit, the best turbo can do is get out of your way. 

> The point of inputs and outputs is just to improve the caching, tighten it up so to speak and make a turbo run as fast as possible?

Yes. `inputs` is a way for turbo to determine whether the cached outputs are still valid. `outputs` is what is actually stored in the cache.
