### ISSUE TITLE
Turborepo hangs when script fails on 1.0.25/1.0.26, but works as expected on 1.0.24

### ISSUE THREAD

**Issue by PabloSzx** [vercel/turborepo#554] opened 2022-01-13 15:07 UTC
### What version of Turborepo are you using?

1.0.24 1.0.25 1.0.26

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux with Node.js v16.13.2

### Describe the Bug

When a pipeline script fails, it hangs. It only happens with 1.0.25/1.0.26, with 1.0.24 it works as expected

With `"turbo": "1.0.26"`, it's stuck:

![](https://i.imgur.com/QgwEThr.png)

With `"turbo": "1.0.24"`, it's not stuck:

![](https://i.imgur.com/Ig4lTr4.png)

![image](https://user-images.githubusercontent.com/8672915/149355493-a79cabad-bedb-40c6-8709-67f0254bacb7.png)

### Expected Behavior

To exit with exit code 1

### To Reproduce

https://github.com/pabloszx/turborepo-hangs

**Comment by Xenfo** [comment] 2022-01-13 20:14
Issue is caused by these lines:
https://github.com/vercel/turborepo/blob/99d11e04bd16d96490810c6efeb36a50a166f3b5/cli/internal/run/run_state.go#L202-L204

**Comment by jaredpalmer** [comment] 2022-01-14 01:27
Fixed in .27

**Closed** 2022-01-14 01:27 UTC
